name: Lint with Ruff

on:
  pull_request:
    branches: [ "main", "ruff-checks"]
  push:
    branches: [ "main", "ruff-checks"]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Ruff
      run: pip install ruff

    - name: Run Ruff Linter
      run: ruff check .
